{
  "debianbug": 853278,
  "description": "An error in the lha_read_file_header_1() function (archive_read_support_format_lha.c) in libarchive 3.2.2 allows remote attackers to trigger an out-of-bounds read memory access and subsequently cause a crash via a specially crafted archive.",
  "releases": {
    "bullseye": {
      "fixed_version": "3.2.1-6",
      "repositories": {
        "bullseye": "3.4.3-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "3.2.1-6",
      "repositories": {
        "buster": "3.3.3-4+deb10u1",
        "buster-security": "3.3.3-4+deb10u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "3.2.1-6",
      "repositories": {
        "sid": "3.4.3-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "3.2.1-6",
      "repositories": {
        "stretch": "3.2.2-2+deb9u2",
        "stretch-security": "3.2.2-2+deb9u2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}